[package]
name = "hello-world-rust"
version = "0.1.0"
authors = ["maitland_j <maitland_j@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
